# core/export_pdf.py
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor
from pathlib import Path
from typing import List, Dict
from datetime import datetime

# Import configuration
try:
    from config import OUTPUT_DIR
except ImportError:
    OUTPUT_DIR = "output"

LOGO = Path("assets/images/logo.png")  # single place
OUTDIR = Path(OUTPUT_DIR)
OUTDIR.mkdir(exist_ok=True)

# Theme styling helper
def _get_theme_colors(theme: str) -> dict:
    if theme == "dark":
        return {
            "bg": HexColor("#121212"),
            "primary": HexColor("#F9FAFB"),
            "accent": HexColor("#10B981"),  # Emerald Green for correct answers
            "text": HexColor("#E5E7EB"),
            "gray": HexColor("#9CA3AF"),
            "line": HexColor("#374151"),
            "header_bg": HexColor("#1F2937"),
            "header_text": HexColor("#F9FAFB"),
            "sub_bg": HexColor("#1E293B")
        }
    else:  # light
        return {
            "bg": HexColor("#FFFFFF"),
            "primary": HexColor("#111111"),
            "accent": HexColor("#15803D"),  # Soft Green for correct answers
            "text": HexColor("#2D3748"),
            "gray": HexColor("#6B7280"),
            "line": HexColor("#E5E7EB"),
            "header_bg": HexColor("#F9FAFB"),
            "header_text": HexColor("#111111"),
            "sub_bg": HexColor("#F1F5F9")
        }

def _draw_header(cnv: canvas.Canvas, title: str, page_num: int = 1, theme: str = "light"):
    """Draw an enhanced header with logo, title, and page information."""
    width, height = A4
    colors = _get_theme_colors(theme)
    
    # Draw page background color
    cnv.setFillColor(colors["bg"])
    cnv.rect(0, 0, width, height, stroke=0, fill=1)
    
    # Draw a subtle header background
    cnv.setFillColor(colors["header_bg"])
    cnv.rect(0, height - 80, width, 80, stroke=0, fill=1)
    
    # Draw a thin bottom line under header
    cnv.setStrokeColor(colors["line"])
    cnv.setLineWidth(1)
    cnv.line(0, height - 80, width, height - 80)
    
    # Draw logo if available
    if LOGO.exists():
        try:
            cnv.drawImage(ImageReader(LOGO.as_posix()), 40, height - 68, width=40, height=40, preserveAspectRatio=True, mask='auto')
        except Exception:
            pass
    
    # Draw title
    cnv.setFillColor(colors["header_text"])
    cnv.setFont("Helvetica-Bold", 18)
    cnv.drawString(95, height - 42, "StudySage")
    
    # Subtitle
    cnv.setFillColor(colors["gray"])
    cnv.setFont("Helvetica", 11)
    cnv.drawString(95, height - 60, title)
    
    # Draw page number
    cnv.setFont("Helvetica", 9)
    cnv.drawRightString(width - 40, height - 42, f"Page {page_num}")
    
    # Draw date and time
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M")
    cnv.drawRightString(width - 40, height - 60, current_time)
    
    # Reset fill color for content
    cnv.setFillColor(colors["text"])

def _draw_footer(cnv: canvas.Canvas, text: str = "Generated by StudySage AI Assistant", theme: str = "light"):
    """Draw a footer with additional information."""
    width, height = A4
    colors = _get_theme_colors(theme)
    
    # Draw a thin line above footer
    cnv.setStrokeColor(colors["line"])
    cnv.setLineWidth(0.5)
    cnv.line(40, 45, width - 40, 45)
    
    cnv.setFillColor(colors["gray"])
    cnv.setFont("Helvetica", 8)
    cnv.drawCentredString(width/2, 30, text)
    cnv.setFillColor(colors["text"])

def _wrap_text(text: str, max_width: int = 80) -> List[str]:
    """Wrap text to fit within a specified width."""
    words = text.split()
    lines = []
    current_line = []
    current_length = 0
    
    for word in words:
        if current_length + len(word) + 1 > max_width:
            if current_line:
                lines.append(" ".join(current_line))
                current_line = [word]
                current_length = len(word)
            else:
                # Handle very long words
                lines.append(word[:max_width])
                current_line = [word[max_width:]]
                current_length = len(current_line[0]) if current_line[0] else 0
        else:
            current_line.append(word)
            current_length += len(word) + 1
    
    if current_line:
        lines.append(" ".join(current_line))
    
    return lines if lines else [""]

def export_summary_to_pdf(summary: str, theme: str = "light") -> str:
    """Export summary to a professionally designed PDF."""
    out = OUTDIR / "summary.pdf"
    cnv = canvas.Canvas(out.as_posix(), pagesize=A4)
    
    # Set document metadata
    cnv.setTitle("StudySage Summary")
    cnv.setAuthor("StudySage AI Assistant")
    cnv.setSubject("AI-Generated Summary")
    
    width, height = A4
    page_num = 1
    colors = _get_theme_colors(theme)
    
    # Draw header
    _draw_header(cnv, "Document Summary", page_num, theme=theme)
    
    # Content settings
    x, y = 40, height - 120
    line_height = 18
    
    # Add a subtitle banner
    cnv.setFillColor(colors["primary"])
    cnv.setFont("Helvetica-Bold", 14)
    cnv.drawString(x, y, "Summary Content")
    
    # Draw simple thin divider below subtitle
    y -= 10
    cnv.setStrokeColor(colors["line"])
    cnv.setLineWidth(1)
    cnv.line(x, y, width - x, y)
    y -= 25
    
    cnv.setFillColor(colors["text"])
    cnv.setFont("Helvetica", 10.5)
    
    # Process summary text with better wrapping
    lines = summary.splitlines()
    for line in lines:
        if not line.strip():
            y -= line_height
            continue
            
        # Wrap long lines
        wrapped_lines = _wrap_text(line, 95)
        for wrapped_line in wrapped_lines:
            if y < 80:  # Need new page
                _draw_footer(cnv, theme=theme)
                cnv.showPage()
                page_num += 1
                _draw_header(cnv, "Document Summary", page_num, theme=theme)
                cnv.setFont("Helvetica", 10.5)
                y = height - 120
            
            cnv.drawString(x, y, wrapped_line)
            y -= line_height
    
    _draw_footer(cnv, theme=theme)
    cnv.save()
    return out.as_posix()

def export_quiz_to_pdf(questions: List[Dict[str, object]], theme: str = "light") -> str:
    """Export quiz to a professionally designed PDF."""
    out = OUTDIR / "quiz.pdf"
    cnv = canvas.Canvas(out.as_posix(), pagesize=A4)
    
    # Set document metadata
    cnv.setTitle("StudySage Quiz")
    cnv.setAuthor("StudySage AI Assistant")
    cnv.setSubject("AI-Generated Quiz Questions")
    
    width, height = A4
    page_num = 1
    colors = _get_theme_colors(theme)
    
    # Draw header
    _draw_header(cnv, "Quiz Questions", page_num, theme=theme)
    
    # Content settings
    x, y = 40, height - 120
    line_height = 20
    question_spacing = 25
    option_spacing = 18
    
    # Add a subtitle
    cnv.setFillColor(colors["primary"])
    cnv.setFont("Helvetica-Bold", 14)
    cnv.drawString(x, y, f"Total Questions: {len(questions)}")
    
    # Subtitle line divider
    y -= 10
    cnv.setStrokeColor(colors["line"])
    cnv.setLineWidth(1)
    cnv.line(x, y, width - x, y)
    y -= 25
    
    cnv.setFillColor(colors["text"])
    cnv.setFont("Helvetica", 10.5)
    
    # Process each question
    for i, q in enumerate(questions, 1):
        # Rough height check: question + options + space requires ~120 units
        if y < 150:  # Need new page
            _draw_footer(cnv, theme=theme)
            cnv.showPage()
            page_num += 1
            _draw_header(cnv, "Quiz Questions", page_num, theme=theme)
            cnv.setFont("Helvetica", 10.5)
            y = height - 120
            # Repeat subtitle line divider on new page
            cnv.setStrokeColor(colors["line"])
            cnv.setLineWidth(1)
            cnv.line(x, y, width - x, y)
            y -= 25
        
        # Question number and text
        cnv.setFillColor(colors["primary"])
        cnv.setFont("Helvetica-Bold", 11.5)
        cnv.drawString(x, y, f"Question {i}:")
        y -= line_height
        
        cnv.setFillColor(colors["text"])
        cnv.setFont("Helvetica", 10.5)
        
        # Wrap and draw question text
        question_text = str(q.get('question', ''))
        question_lines = _wrap_text(question_text, 90)
        for line in question_lines:
            if y < 80:  # Need new page
                _draw_footer(cnv, theme=theme)
                cnv.showPage()
                page_num += 1
                _draw_header(cnv, "Quiz Questions", page_num, theme=theme)
                cnv.setFont("Helvetica", 10.5)
                y = height - 120
            
            cnv.drawString(x + 15, y, line)
            y -= line_height
        
        y -= 8  # Small space before options
        
        # Options
        cnv.setFont("Helvetica", 10)
        options = q.get('options', [])
        if isinstance(options, list):
            for j, opt in enumerate(options, 1):
                if y < 80:  # Need new page
                    _draw_footer(cnv, theme=theme)
                    cnv.showPage()
                    page_num += 1
                    _draw_header(cnv, "Quiz Questions", page_num, theme=theme)
                    cnv.setFont("Helvetica", 10)
                    y = height - 120
                
                cnv.drawString(x + 25, y, f"{chr(64+j)}. {str(opt)}")  # A, B, C, D...
                y -= option_spacing
        
        y -= 8  # Space before answer
        
        # Answer
        if y < 80:  # Need new page
            _draw_footer(cnv, theme=theme)
            cnv.showPage()
            page_num += 1
            _draw_header(cnv, "Quiz Questions", page_num, theme=theme)
            y = height - 120
        
        answer_text = str(q.get('answer', ''))
        cnv.setFillColor(colors["accent"])
        cnv.setFont("Helvetica-Bold", 10)
        cnv.drawString(x + 25, y, f"Correct Answer: {answer_text}")
        cnv.setFillColor(colors["text"])
        
        y -= (question_spacing - 10)
        
        # Draw a very light separator line between questions
        if i < len(questions):
            cnv.setStrokeColor(colors["line"])
            cnv.setLineWidth(0.5)
            cnv.line(x, y + 10, width - x, y + 10)
            y -= 10
    
    _draw_footer(cnv, "StudySage Quiz - Test your knowledge!", theme=theme)
    cnv.save()
    return out.as_posix()