[theme]
base = "light"
primaryColor = "#18181b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f4f5"
textColor = "#18181b"
font = "sans serif"

[client]
showErrorDetails = true

[browser]
gatherUsageStats = false
